import { readFileSync } from 'node:fs';
import { fileURLToPath, URL } from 'node:url';
import react from '@vitejs/plugin-react';
import { defineConfig, loadEnv, type Plugin } from 'vite';

const packageJson = JSON.parse(
  readFileSync(new URL('./package.json', import.meta.url), 'utf8'),
) as { version: string };

function buildServiceWorkerSource(version: string, assets: string[]): string {
  return `/* Generated by vite.config.ts. Do not edit dist/sw.js directly. */
const CACHE_NAME = ${JSON.stringify(`pushbridge-${version}`)};
const APP_SHELL = ${JSON.stringify(assets)};
const API_PATHS = ['/api/', '/mock-storage/', '/health', '/realtime'];

function localDatabaseName(namespace) {
  const safe = String(namespace || 'default').toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
  return 'pushbridge-' + (safe || 'default') + '-v2';
}

function openLocalDatabase(namespace) {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(localDatabaseName(namespace));
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error || new Error('IndexedDB open failed'));
  });
}

function asBytes(value) {
  if (value instanceof Uint8Array) return value;
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (value && ArrayBuffer.isView(value)) return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
  throw new Error('E2EE account key is unavailable');
}

async function readAccountKey(db) {
  return new Promise((resolve, reject) => {
    if (!db.objectStoreNames.contains('e2eeKeys')) { reject(new Error('E2EE key store is unavailable')); return; }
    const request = db.transaction('e2eeKeys', 'readonly').objectStore('e2eeKeys').get('account-key');
    request.onsuccess = () => request.result ? resolve(request.result) : reject(new Error('E2EE account key is unavailable'));
    request.onerror = () => reject(request.error || new Error('E2EE key read failed'));
  });
}

async function decryptFileBlob(db, fileId, blob) {
  const input = new Uint8Array(await blob.arrayBuffer());
  if (input.byteLength < 53 || input[0] !== 80 || input[1] !== 66 || input[2] !== 70 || input[3] !== 69 || input[4] !== 1) throw new Error('Invalid encrypted File container');
  const keyVersion = new DataView(input.buffer, input.byteOffset + 5, 4).getUint32(0, false);
  const record = await readAccountKey(db);
  if (record.key_version !== keyVersion) throw new Error('Encrypted File key version is unavailable');
  const material = await crypto.subtle.importKey('raw', asBytes(record.key_bytes), 'HKDF', false, ['deriveKey']);
  const key = await crypto.subtle.deriveKey({
    name: 'HKDF', hash: 'SHA-256', salt: input.slice(9, 25), info: new TextEncoder().encode('pushbridge/file/v1/' + keyVersion),
  }, material, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
  const plaintext = await crypto.subtle.decrypt({
    name: 'AES-GCM', iv: input.slice(25, 37), additionalData: new TextEncoder().encode('pushbridge/file/v1/' + fileId),
  }, key, input.slice(37));
  return new Blob([plaintext], { type: 'application/octet-stream' });
}

async function cacheFileFromPush(data) {
  const item = data?.file_download;
  if (!item?.download_url || !item?.file_id || !item?.push_id || !data?.storage_namespace) return false;
  const downloadTarget = new URL(item.download_url, self.location.origin);
  if (downloadTarget.origin !== self.location.origin) throw new Error('Cross-origin background download rejected');
  const response = await fetch(downloadTarget.href, { cache: 'no-store', credentials: 'omit' });
  if (!response.ok) throw new Error('Background file download failed: ' + response.status);
  let blob = await response.blob();
  if (Number.isFinite(item.size) && item.size >= 0 && blob.size !== item.size) {
    throw new Error('Background file size mismatch');
  }
  const db = await openLocalDatabase(data.storage_namespace);
  try {
    if (item.encrypted) blob = await decryptFileBlob(db, item.file_id, blob);
    const transaction = db.transaction(['cachedFiles', 'pushes'], 'readwrite');
    transaction.objectStore('cachedFiles').put({
      file_id: item.file_id,
      push_id: item.push_id,
      name: item.name || ('ファイル ' + item.file_id),
      mime_type: item.mime_type || 'application/octet-stream',
      size: blob.size,
      blob,
      cached_at: new Date().toISOString(),
      last_accessed_at: new Date().toISOString(),
      pinned: Boolean(item.pinned),
    });
    const pushes = transaction.objectStore('pushes');
    const getPush = pushes.get(item.push_id);
    getPush.onsuccess = () => {
      if (getPush.result) pushes.put({ ...getPush.result, local_file_cached: true, local_file_delivery: 'cached' });
    };
    await new Promise((resolve, reject) => {
      transaction.oncomplete = () => resolve();
      transaction.onerror = () => reject(transaction.error || new Error('IndexedDB write failed'));
      transaction.onabort = () => reject(transaction.error || new Error('IndexedDB write aborted'));
    });
  } finally {
    db.close();
  }
  return true;
}

async function acknowledgeFileDelivery(data, state, failureCode) {
  const item = data?.file_delivery;
  if (!item?.delivery_id || !item?.token) return false;
  const target = new URL(item.events_url || ('/api/v1/file-deliveries/' + encodeURIComponent(item.delivery_id) + '/events'), self.location.origin);
  if (target.origin !== self.location.origin) throw new Error('Cross-origin delivery acknowledgement rejected');
  const response = await fetch(target.href, {
    method: 'POST',
    cache: 'no-store',
    credentials: 'omit',
    headers: {
      authorization: 'Bearer ' + item.token,
      'content-type': 'application/json',
    },
    body: JSON.stringify({ state, ...(failureCode ? { failure_code: failureCode } : {}) }),
  });
  if (!response.ok) throw new Error('Delivery acknowledgement failed: ' + response.status);
  return true;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.allSettled(APP_SHELL.map((asset) => cache.add(asset)));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith('pushbridge-') && key !== CACHE_NAME).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (API_PATHS.some((path) => url.pathname === path || url.pathname.startsWith(path))) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) {
          const cache = await caches.open(CACHE_NAME);
          await cache.put('/index.html', response.clone());
        }
        return response;
      } catch {
        return (await caches.match('/index.html')) || (await caches.match('/')) || Response.error();
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    const network = fetch(request).then(async (response) => {
      if (response.ok && response.type === 'basic') {
        const cache = await caches.open(CACHE_NAME);
        await cache.put(request, response.clone());
      }
      return response;
    }).catch(() => undefined);

    return cached || (await network) || Response.error();
  })());
});

self.addEventListener('push', (event) => {
  let data = {};
  try {
    data = event.data?.json() ?? {};
  } catch {
    data = { body: event.data?.text() ?? '新しいPushがあります。' };
  }

  const title = data.title || 'Pushbridge';
  const options = {
    body: data.body || '新しいPushがあります。',
    icon: '/icons/icon-192.png',
    badge: '/icons/badge-96.png',
    data: { url: data.url || '/#/timeline' },
    tag: data.tag || 'pushbridge-update',
  };
  event.waitUntil((async () => {
    let cached = false;
    await acknowledgeFileDelivery(data, 'fetching').catch(() => false);
    try {
      cached = await cacheFileFromPush(data);
      if (cached) await acknowledgeFileDelivery(data, 'cached');
    } catch {
      await acknowledgeFileDelivery(data, 'failed_retryable', 'background_fetch_failed').catch(() => false);
      // Cursor sync retains the alias and later marks the undelivered file explicitly.
    }
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of clients) client.postMessage({ type: 'WEB_PUSH_RECEIVED', fileCached: cached });
    await self.registration.showNotification(title, options);
  })());
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = event.notification.data?.url || '/#/timeline';
  event.waitUntil((async () => {
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of clients) {
      if ('focus' in client) {
        await client.focus();
        client.postMessage({ type: 'NAVIGATE', url: target });
        return;
      }
    }
    await self.clients.openWindow(target);
  })());
});
`;
}

function pwaServiceWorkerPlugin(): Plugin {
  return {
    name: 'pushbridge-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      for (const output of Object.values(bundle)) {
        if (output.type === 'chunk') output.code = output.code.replace(/^[\t ]+$/gm, '');
      }

      const generated = Object.keys(bundle)
        .filter((fileName) => !fileName.endsWith('.map') && fileName !== 'sw.js')
        .map((fileName) => `/${fileName}`);

      const assets = Array.from(new Set([
        '/',
        '/index.html',
        '/manifest.webmanifest',
        '/favicon.svg',
        '/icons/icon-192.png',
        '/icons/icon-512.png',
        '/icons/icon-maskable-512.png',
        '/icons/apple-touch-icon.png',
        '/icons/badge-96.png',
        ...generated,
      ]));

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: buildServiceWorkerSource(packageJson.version, assets),
      });
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');
  const apiTarget = env.API_PROXY_TARGET || 'http://127.0.0.1:8000';

  return {
    plugins: [react(), pwaServiceWorkerPlugin()],
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    define: {
      __APP_VERSION__: JSON.stringify(packageJson.version),
    },
    server: {
      host: '127.0.0.1',
      port: 5173,
      strictPort: true,
      proxy: {
        '/api': {
          target: apiTarget,
          changeOrigin: false,
          rewrite: (path) => path.replace(/^\/api(?=\/|$)/, ''),
        },
        '/mock-storage': {
          target: apiTarget,
          changeOrigin: false,
        },
        '/health': {
          target: apiTarget,
          changeOrigin: false,
        },
        '/realtime': {
          target: apiTarget,
          changeOrigin: false,
          ws: true,
        },
      },
    },
    build: {
      target: 'es2022',
      sourcemap: false,
      outDir: '../../infra/cloudflare/app/dist',
      emptyOutDir: true,
    },
  };
});
